### ISSUE TITLE
Plex Roadmap

### ISSUE THREAD

**Issue by Telesphoreo** [plexusorg/Plex#4]
For 1.0
- [x] Add rest of punishment commands (mute, tempban)
- [x] Add adminchat
- [x] Add a configurable entity wiping system
- [x] Add permanent bans
- [x] Add command blocker RegEx) *Note: I originally said I wanted this as a module. I changed my mind, this should be in the Plex plugin itself*
- [x] Add update checking to warn server owners if their version of Plex is out of date
- [x] Global gamerules
- [x] Lockup command 😈 
- [ ] Event blocking commands (blockedit)
  - [x] blockedits
  - [ ] blockpvp
- [x] Add a smite command

Potentially for 1.0:
- [x] Plugin API as a subproject
- [ ] "Fun" things (maybe)
  - [ ] Jumppads
  - [ ] Clownfish
- [ ] Add a myadmin command to manage IPs, set login message, etc

For future and beyond
- [ ] Toggleable events (toggleredstone, togglepvp, etc)
  - [x] toggleredstone
  - [ ] togglepvp
  - [x] toggleentities
- [ ] Cages (?)
- [ ] Shop (as a module)
- [x] HTTPD module
- [ ] Add settings and restrictions for adminworld / masterbuilderworld
- [ ] Rewrite command system so worlds like flatlands and adminworld aren't hardcoded
- [x] Reflections API for command and listener loading
- [ ] (Potentially) Add 2FA authentication
